export { Close, Description, Portal, Title, Trigger } from '@/components/dialog/index.parts'
export { default as Backdrop } from './drawer-backdrop.vue'
export { default as Content } from './drawer-content.vue'
export { default as IndentBackground } from './drawer-indent-background.vue'
export { default as Indent } from './drawer-indent.vue'
export { default as Popup } from './drawer-popup.vue'
export { default as Provider } from './drawer-provider.vue'
export { default as Root } from './drawer-root.vue'
export { default as SwipeArea } from './drawer-swipe-area.vue'
export { default as Viewport } from './drawer-viewport.vue'
export { createDrawerHandle as createHandle } from './handle'
export type { DrawerHandle as Handle } from './handle'
